# Generated by Django 4.2.7 on 2024-01-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bankdate', models.DateField()),
                ('Bankname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('AccountNumber', models.CharField(max_length=50)),
                ('IFSCcode', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
    ]
